@startuml
    start
        :пользователь заходит на сайт;
        :заполнение полей "email" и "пароль";
        if(данные верны?) then (да)
            :пользователь авторизован;
            switch (доступные действия админа)
                case(аренда)
                    :выбрать фильм;
                    :нажать на кнопку арендовать;
                    :заполнить форму аренды;
                    :подтверждение аренды;
                    :фильм арендован;
                    stop
                case(покупка)
                    :выбрать фильм;
                    :нажать на кнопку купить;
                    :заполнить форму покупки;
                    :подтверждение покупки;
                    :фильм куплен;
                    stop
                case(профиль)
                    switch(доступные действия пользователя)
                        case(просмотр арендованых ранее фильмов)
                            :список всех арендованых фильмов;
                        case(просмотр купленых ранее фильмов)
                            :список всех купленых фильмов;
                        case(редактирование профиля)
                            :изменение поолей с данными пользователя;
                            :выводится сообщение что данные обновлены;
                            stop 
                    endswitch
                    stop
                case(редактировать фильм)
                    :выбрать фильм;
                    :нажать на кнопку редактировать;
                    :изменение поолей с информацией о фильме;
                    :выводится сообщение что данные обновлены;
                    stop
                case(удалить фильм)
                    :выбрать фильм;
                    :нажать на кнопку удалить;
                    :подтвердить удаление;
                    :фильм удалён;
                    stop
                case(добавить фильм)
                    :нажать на кнопку добавить фильм;
                    :заполнить форму фильма;
                    :фильм добавлен;
                    stop
                case(выход)
                    end
            endswitch
        else (нет)
            :выводится сообщение что данные не верны; 
            stop   
        endif
@enduml